" generated by tools/mknvim.py from demo/logo.c's words -- never edit
" LOGO as the machine has it (.LGO; LOGO runs them from NVIM's :Run)
if exists("b:current_syntax") | finish | endif
syn case ignore
syn iskeyword @,48-57,_,?,.
syn keyword k4logoControl END IF IFELSE MAKE OP OUTPUT REPEAT STOP TO
syn keyword k4logoWord ABS BACK BK BYE CLEAN CLEARSCREEN COS CS ED EDIT FD FILL FORWARD HEADING
syn keyword k4logoWord HELP HIDETURTLE HOME HT INT LEFT LOAD LT PD PENDOWN PENUP PR PRINT PU RANDOM
syn keyword k4logoWord REPCOUNT RIGHT RT SETH SETHEADING SETPC SETPENCOLOR SETPENCOLOUR SETX SETXY
syn keyword k4logoWord SETY SHOW SHOWTURTLE SIN SQRT ST XCOR YCOR
syn match k4logoVar ":[A-Za-z_][A-Za-z0-9_.]*"
syn match k4logoQuoted +"[A-Za-z_][A-Za-z0-9_.?]*+
syn match k4logoNumber "\<\d\+\(\.\d*\)\?\>"
syn match k4logoComment ";.*$"
hi def link k4logoControl Statement
hi def link k4logoWord    Function
hi def link k4logoVar     Identifier
hi def link k4logoQuoted  String
hi def link k4logoNumber  Number
hi def link k4logoComment Comment
let b:current_syntax = "k4510logo"
