" generated by tools/mknvim.py from tools/k4510-bas's word lists -- never edit
" K4510 BASIC, the machine's BASIC (.BAS; :Run compiles it with k4510-bas and runs it)
if exists("b:current_syntax") | finish | endif
syn case ignore
syn iskeyword @,48-57,_,$
syn keyword k4basicStatement AND BOX CALL CASE CIRCLE CLOSE CLS COLOR CONST DEF DIM DO ELSE ELSEIF END
syn keyword k4basicStatement EXIT FOR FUNCTION GCLS GET GOSUB GOTO GRAPHICS IF INPUT IS LET LINE LOCATE
syn keyword k4basicStatement LOOP MOD MOVSPR NEXT NOT ON OPEN OR PALETTE PLAY PLOT POKE PRINT RANDOMIZE
syn keyword k4basicStatement READ REPEAT RESTORE RETURN SELECT SHELL SLEEP SOUND SPRDEF SPRITE SPROFF
syn keyword k4basicStatement SPRVEL STEP STOP SUB SWAP THEN TO TRI UNTIL WAITFRAME WEND WHILE XOR
syn keyword k4basicFunction ABS ASC ATN CHR$ COS EOF EXP FIX FRAMES GHEIGHT GWIDTH HEX$ HIT HITBG INKEY$
syn keyword k4basicFunction INSTR INT JOY KEYDOWN LCASE$ LEFT$ LEN LOG LTRIM$ MID$ PEEK RIGHT$ RND RTRIM$
syn keyword k4basicFunction SGN SIN SPACE$ SPRX SPRY SQR STR$ STRING$ TAN TIMER UCASE$ VAL
syn match k4basicLineNr "^\s*\d\+"
syn match k4basicNumber "\<\d\+\(\.\d*\)\?\([eE][-+]\?\d\+\)\?\>"
syn match k4basicNumber "\$\x\+\>"
syn match k4basicNumber "%[01]\+\>"
syn region k4basicString start=+"+ end=+"+ oneline
syn match k4basicComment "\<REM\>.*$"
syn match k4basicData "\<DATA\>.*$"
hi def link k4basicStatement Statement
hi def link k4basicFunction  Function
hi def link k4basicLineNr    LineNr
hi def link k4basicNumber    Number
hi def link k4basicString    String
hi def link k4basicComment   Comment
hi def link k4basicData      Constant
let b:current_syntax = "k4510basic"
