" generated by tools/mknvim.py from basic/basic.asm's keyword table -- never edit
" BASIC as the machine has it: EhBASIC with its graphics and sprites, and
" Microsoft's 1977 BASIC (.BAS; MSBASIC runs them from NVIM's :Run)
if exists("b:current_syntax") | finish | endif
syn case ignore
syn iskeyword @,48-57,_,$
syn keyword k4basicStatement AND BITCLR BITSET CALL CLEAR CONT DEC DEF DIM DO DOKE ELSE END EOR FN FOR
syn keyword k4basicStatement GCLS GET GOSUB GOTO GRAPHICS IF INC INPUT IRQ LET LINE LIST LOAD LOOP NEW
syn keyword k4basicStatement NEXT NMI NOT NULL OFF ON OR PALETTE PI PLOT POKE PRINT READ RESTORE RETIRQ
syn keyword k4basicStatement RETNMI RETURN RUN SAVE SPRDEF SPRITE SPROFF STEP STOP SWAP THEN TO TRI TWOPI
syn keyword k4basicStatement UNTIL WAIT WHILE WIDTH
syn keyword k4basicFunction ABS ASC ATN BIN$ BITTST CHR$ COS DEEK EXP FRE HEX$ INT LCASE$ LEFT$ LEN
syn keyword k4basicFunction LOG MAX MID$ MIN PEEK POS RIGHT$ RND SADD SGN SIN SPC SQR STR$ TAB TAN UCASE$
syn keyword k4basicFunction USR VAL VARPTR
syn match k4basicLineNr "^\s*\d\+"
syn match k4basicNumber "\<\d\+\(\.\d*\)\?\([eE][-+]\?\d\+\)\?\>"
syn match k4basicNumber "\$\x\+\>"
syn match k4basicNumber "%[01]\+\>"
syn region k4basicString start=+"+ end=+"+ oneline
syn match k4basicComment "\<REM\>.*$"
syn match k4basicData "\<DATA\>.*$"
hi def link k4basicStatement Statement
hi def link k4basicFunction  Function
hi def link k4basicLineNr    LineNr
hi def link k4basicNumber    Number
hi def link k4basicString    String
hi def link k4basicComment   Comment
hi def link k4basicData      Constant
let b:current_syntax = "k4510basic"
