/* ---- SYS $D500 ---------------------------------------------------------- */
#include <stdio.h>
#include <string.h>
#include <strings.h>
#include <ctype.h>
#include <time.h>
#include "io.h"
#include "io_int.h"
#include "mem.h"
#include "ui/settings.h"      /* the CPU clock request at $D523 */
#include "term.h"
#include "vicky.h"
#include "state.h"
extern uint32_t mem_rom_base;
uint32_t sys_frames;
static uint8_t  sys_reg[0x10];
/* The build, not the generation.  The Makefile stamps git describe in here, so
 * a BUG report names the exact commit it came from; without that both this and
 * ROM_VERSION only say which era the machine is from.  16 bytes, NUL included. */
#include "build.h"        /* generated by the Makefile from git; regenerated only when
                           * the commit changes, so io.o rebuilds exactly when it must */
#ifndef K4510_BUILD
#define K4510_BUILD "k4510 0.3"
#endif
const char sys_version[16] = K4510_BUILD;
/* $D522: what is beneath the machine.  The guest cannot otherwise tell a
 * desktop window from the K4510 Linux -- the ROM bytes are the same --
 * and BUG and INFO have to say which one an issue came from.  The frontend
 * sets it: 0 = a desktop (or a container on one), 1 = the K4510 Linux. */
int io_host_kind;
uint8_t io_battery = 0xFF;    /* $D53A: none until the frontend finds one */
uint8_t io_frame = 11, io_frame_follow = 1;
char io_palname[64]; int io_palname_new;
uint8_t io_vidcap_req, io_vidcap_state; uint16_t io_vidcap_k;   /* $D548: SETUP's pixel budget, measured by the frontend */           /* $D547: the kept palette, and "the machine loaded another" */
static char palname_in[64]; static uint8_t palname_n, palname_rd;   /* the frame: dark grey, the palette's */
uint16_t io_batt_min = 0xFFFF; /* the time it has left, for the band: none until the frontend has one */
uint8_t io_net = 0xFF, io_net_q;   /* the network, for the bottom band: NET_*, $FF not known; Wi-Fi's link quality, % */
/* ---- the title: what the machine is running, for the top status band ----
 * Doc, 2026-09-14: the top band's left should say "K/OS for the shell,
 * EhBasic for Ehbasic ... and also reflect the basic file being edited ...
 * and if we are in *VI or *EDIT mode".  A stack of entries, a program and
 * the file it has, drawn by the frontend as "EhBASIC PROG.BAS > VI
 * EDITTMP.BAS" (sdl/main.c bands_overlay; K/OS only at the prompt).  The ROM says WHEN -- SYS+$41: 1
 * as it runs a program, 2 when it comes back, 4 at its cold start -- and
 * this file says WHAT: the .prg the file device loaded last is the name the
 * next push takes, and a file of a known kind that the program at the top
 * loads or saves becomes that entry's file.  So no program had to learn
 * anything.  SYS+$40 appends a character to the top entry's name and SYS+$41
 * = 3 empties it, for a program that wants to name itself. */
#define TITLE_DEPTH 8
static struct { char prog[24]; char file[40]; uint8_t resize; } title_stack[TITLE_DEPTH] = { { "K/OS", "", 0 } };   /* resize: SYS+$46 */
static uint8_t resize_due;                         /* SYS+$46 bit7: the screen changed under a program that asked to be told */
static int title_depth = 1;
static char title_next[24];
static void title_cmd(uint8_t c)
{
    if (c == 1) {                                     /* a program starts: its name, as the file device saw it load */
        if (title_depth < TITLE_DEPTH) {
            snprintf(title_stack[title_depth].prog, sizeof title_stack[0].prog, "%s", title_next[0] ? title_next : "?");
            title_stack[title_depth].file[0] = 0; title_stack[title_depth].resize = 0; title_depth++;
        }
        title_next[0] = 0;
    } else if (c == 2) { if (title_depth > 1) title_depth--; mouse_host_release(); }   /* it came back (and its $D110 wish ends with it) */
    else if (c == 3) { title_stack[title_depth - 1].prog[0] = 0; title_stack[title_depth - 1].file[0] = 0; }
    else if (c == 4) { mouse_host_release(); title_depth = 1; title_stack[0].resize = 0; resize_due = 0; strcpy(title_stack[0].prog, "K/OS"); title_stack[0].file[0] = 0; title_next[0] = 0; }
}
/* SYS+$44: a program names the file it has in front -- PROG's tabs switch
 * without loading anything, so title_file() never hears of it.  0 clears
 * the top entry's file, any other byte adds a character. */
static void title_file_char(uint8_t c)
{
    char *f = title_stack[title_depth - 1].file; size_t n = strlen(f);
    if (!c) f[0] = 0;
    else if (c >= 0x20 && n < sizeof title_stack[0].file - 1) { f[n] = (char) c; f[n + 1] = 0; }
}
static void title_char(uint8_t c)
{
    char *p = title_stack[title_depth - 1].prog; size_t n = strlen(p);
    if (c >= 0x20 && n < sizeof title_stack[0].prog - 1) { p[n] = (char) c; p[n + 1] = 0; }
}
/* the file device opened, loaded or saved HOST path P for the machine */
void title_file(const char *p)
{
    static const char *const kinds[] = { ".BAS", ".LGO", ".BBC", ".PAS", ".C", ".RX", ".GMI", ".TXT", NULL };
    static const struct { const char *stem, *name; } names[] = {
        { "ehbasic", "EhBASIC" }, { "logo", "LOGO" }, { "rx", "RX" }, { NULL, NULL } };
    const char *b = strrchr(p, '/'), *dot;
    b = b ? b + 1 : p;
    dot = strrchr(b, '.');
    if (!dot) return;
    if (!strcasecmp(dot, ".prg")) {                   /* a program: the next push takes its name */
        size_t n = (size_t)(dot - b); char stem[24];
        if (n >= sizeof stem) n = sizeof stem - 1;
        memcpy(stem, b, n); stem[n] = 0;
        for (int i = 0; names[i].stem; i++) if (!strcasecmp(stem, names[i].stem)) { snprintf(title_next, sizeof title_next, "%s", names[i].name); return; }
        for (size_t i = 0; i < n; i++) stem[i] = (char) toupper((unsigned char) stem[i]);
        snprintf(title_next, sizeof title_next, "%s", stem);
        return;
    }
    if (title_depth < 2) return;                      /* the shell's own files (STARTUP.BAT, EXEC) name nothing */
    for (int i = 0; kinds[i]; i++)
        if (!strcasecmp(dot, kinds[i])) {
            const char *prog = title_stack[title_depth - 1].prog;
            /* EhBASIC's *VI and *EDIT go by way of EDITTMP.BAS: the program keeps its own name */
            if (!strcasecmp(b, "EDITTMP.BAS") && strcmp(prog, "VI") && strcmp(prog, "EDIT")) return;
            snprintf(title_stack[title_depth - 1].file, sizeof title_stack[0].file, "%s", b);
            return;
        }
}
void io_frame_tick(void) { sys_frames++; seq_tick(); s2_pump(); term_tick(); dbg_frame(); }
unsigned sys_cpu_khz = 40500;
void io_set_cpu_khz(unsigned khz) { sys_cpu_khz = khz; }   /* the frontend, from the CPU clock setting */
static void sys_latch(void)
{
    time_t t = time(NULL); struct tm *m = localtime(&t);
    sys_reg[0] = (uint8_t)(sys_cpu_khz & 0xFF); sys_reg[1] = (uint8_t)(sys_cpu_khz >> 8);
    sys_reg[2] = 256 & 0xFF;   sys_reg[3] = 256 >> 8;
    sys_reg[5] = m->tm_sec; sys_reg[6] = m->tm_min; sys_reg[7] = m->tm_hour;
    sys_reg[8] = m->tm_mday; sys_reg[9] = m->tm_mon + 1;
    sys_reg[10] = (m->tm_year + 1900) & 0xFF; sys_reg[11] = (m->tm_year + 1900) >> 8;
    sys_reg[12] = m->tm_wday;
}
static uint8_t sys_opts;                 /* the menu's switches, readable by the guest */
uint16_t io_audio_gaps;                   /* the frontend counts: audio callbacks that found nothing to play */
static int mode_acked;
void io_set_opts(uint8_t v)
{
    sys_opts = v;
    vicky_set_user_bands(v & SYSOPT_STATUS);   /* the F12 switch is VICKY's BANDCTL bit0: she owns the layout (2026-10-01) */
}
static uint8_t sys_band_top = 1, sys_band_bot = 1, sys_clockfmt;
static uint8_t sys_mode;                   /* $D53C: the mode the host wants, whole (mode+1; 0 none) -- $D521's three bits stop at MODE 6 */
void io_set_mode(uint8_t m1) { sys_mode = m1; }
static uint8_t sys_div;                    /* $D53D: MODE 5's scale on the panel, the IDR the host wants (2026-10-07); 0 = 1 */
void io_set_mode_div(uint8_t div) { sys_div = div; }
void io_set_bands(uint8_t top, uint8_t bot, uint8_t clockfmt)
{ sys_band_top = top; sys_band_bot = bot; sys_clockfmt = clockfmt; }
uint8_t io_clockfmt(void) { return sys_clockfmt; }   /* for JIM's band clock */
int  io_mode_acked(void) { int a = mode_acked; mode_acked = 0; return a; }
/* SETUP measures the machine and then asks to keep the answer.  The guest
 * cannot write k4510.cfg -- it is outside the machine's filesystem -- and has
 * no business knowing what a host fingerprint is, so it writes SYS+$28 and the
 * frontend does both.  Reading SYS+$28 says whether this host has been
 * measured at all, which is what the banner tells the user about. */
static int clock_measured, adopt_req;
void io_set_clock_measured(int yes) { clock_measured = yes ? 1 : 0; }
int  io_clock_measured(void) { return clock_measured; }   /* asked back: the governor says a different
                                                           * thing when SETUP's answer is the one standing */
int  io_adopt_requested(void) { int a = adopt_req; adopt_req = 0; return a; }
/* SETUP sweeps the ladder and starves the sound on purpose at the top of it.
 * The governor's whole job is to step down when the sound starves, so left
 * running it changes the clock under the program measuring it -- which it did,
 * 2026-08-27: the sweep came out non-monotonic and nothing reached 60 fps.
 * SYS+$29 says a measurement is in progress and the governor stands down. */
static int measuring;
int  io_measuring(void) { return measuring; }
/* What "choppy" actually is, since 952daa6.  The gap counter asks whether the
 * ring ran dry, and that fix stops it running dry by clocking the sound on
 * without the CPU when the machine is late -- so gaps read 0 across the whole
 * band where a host is merely losing, and Doc could hear drops on rows both
 * BENCH and SETUP called clean.  This counts the samples that came from that
 * top-up rather than from a frame the machine ran: it is the sound the
 * machine did not make, which is the sound he is hearing. */
uint16_t io_audio_fill;

/* A real-time millisecond counter at SYS+$36..$39 (32-bit, little endian).
 *
 * The frame counter at SYS+$0D counts frames the machine RENDERED, which is
 * the right clock for anything that wants to be in step with the picture and
 * the wrong one for anything that wants to be in step with the world: when
 * the host runs long, frames stretch and anything paced by them stretches
 * with them.  OPLPLAY's music did exactly that on the Pi.
 *
 * It is read through the host's own clock at the moment the guest asks,
 * rather than latched once a frame -- latching would hand back the same
 * granularity the frame counter already has and fix nothing. */
static uint32_t (*ms_source)(void);
void io_set_ms_source(uint32_t (*fn)(void)) { ms_source = fn; }
static uint32_t sys_ms(void) { return ms_source ? ms_source() : 0; }

uint8_t sys_read(uint8_t r)
{
    uint8_t dv;
    if (r == 4) { sys_latch(); return 0; }
    if (r < 4) { sys_latch(); return sys_reg[r]; }
    if (r < 0x0D) return sys_reg[r];
    if (r < 0x10) return (uint8_t)(sys_frames >> ((r - 0x0D) * 8));
    if (r == 0x46) return (uint8_t)(title_stack[title_depth - 1].resize | resize_due);
    if (r == 0x48) return io_vidcap_state;                /* VIDCAP: 0 1 2 3 */
    if (r == 0x49 || r == 0x4A) return (uint8_t)(io_vidcap_k >> (8 * (r - 0x49)));
    if (r == 0x47) { uint8_t c = palname_rd < sizeof io_palname ? (uint8_t) io_palname[palname_rd] : 0; if (c) palname_rd++; else palname_rd = 0; return c; }   /* PALNAME */   /* RESIZE: the wish, and bit7 one waiting */
    if (r < 0x20) return (uint8_t)sys_version[r - 0x10];
    if (r == 0x20) return (uint8_t)(mem_rom_base >> 8);
    if (r == 0x21) return sys_opts;
    if (r == 0x2D) return sys_band_top;      /* rows in the top band */
    if (r == 0x2E) return sys_band_bot;      /* rows in the bottom band */
    if (r == 0x2F) return sys_clockfmt;      /* bit0 24-hour; bits1-2 the date order */
    if (r == 0x3C) return sys_mode;          /* the wanted video mode, mode+1 (hd-modes: MODE 5-7 need it) */
    if (r == 0x3D) return sys_div;           /* ...and for MODE 5, its scale on the panel */
    if (r == 0x22) return (uint8_t)io_host_kind;  /* what is beneath the machine, for BUG and INFO */
    /* The clock's index in the frontend's ladder.  Deliberately NOT documented
     * as a fixed table: the ladder is reordered when steps are added, and a
     * guest that knows a clock by its position gets it wrong the day that
     * happens (BENCH did, 2026-08-27).  Write past the end to learn the
     * highest index -- the write clamps -- and read SYS+0/1/0x26 to see what
     * a step actually became. */
    if (r == 0x23) { int v = settings_get(SET_CPU_CLOCK), f = settings_first(SET_CPU_CLOCK);   /* the ladder as the machine sees it starts at the cap; */
                     return (uint8_t)(v > f ? v - f : 0); }                                    /* a value never loaded (headless) reads as its top, not -4 */
    if (r == 0x24) return (uint8_t)(io_audio_gaps & 0xFF);       /* audio callbacks that found the ring empty, since last cleared */
    if (r == 0x25) return (uint8_t)(io_audio_gaps >> 8);
    if (r == 0x27) return (uint8_t)(settings_choices(SET_CPU_CLOCK) - settings_first(SET_CPU_CLOCK));
    if (r == 0x28) return (uint8_t)clock_measured;                /* 0: no measured clock for this host yet -- run SETUP */
    if (r == 0x29) return (uint8_t)measuring;
    if (r == 0x2A) return (uint8_t)(io_audio_fill & 0xFF);       /* filled samples since last cleared, saturating */
    if (r == 0x2B) return (uint8_t)(io_audio_fill >> 8);
    if (r == 0x26) return (uint8_t)(sys_cpu_khz >> 16);   /* the clock in kHz needs a third byte: SYS+0/1 alone stop at 65.5 MHz, and the ladder goes to 202500 */
    if (dbg_reg_read(r, &dv)) return dv;     /* WATCH $30-$35, DUMP $F0, $F2 (core/debug.c) */
    if (r >= 0x36 && r <= 0x39) return (uint8_t)(sys_ms() >> (8 * (r - 0x36)));   /* the wall clock, in ms */
    if (r == 0x3A) return io_battery;        /* the host's battery: % in bits 0-6, bit 7 on AC / charging, $FF none */
    if (r >= 0x50 && r <= 0x5C) return mem_fence_read((uint8_t)(r - 0x50));   /* the stack fence (core/mem.h) */
    if (r == 0x43) return idea_next();        /* IDEA: the brainshot's name, a byte at a time, then 0 */
    return 0xFF;
}
void sys_write(uint8_t r, uint8_t v)
{
    if (r >= 0xE0 && r <= 0xE3) seq_write((uint8_t)(r - 0xE0), v);
    dbg_reg_write(r, v);                                  /* WATCH $30-$34, DUMP $F0-$F2 */
    if (r == 0x23) settings_set(SET_CPU_CLOCK, v + settings_first(SET_CPU_CLOCK));   /* a program asks for a clock; the frontend applies it next frame (BENCH sweeps them) */
    if (r == 0x24) { io_audio_gaps = 0; io_audio_fill = 0; }   /* any write clears both audio counts */
    if (r == 0x40) title_char(v);                         /* the title: a character for the top entry's name */
    if (r == 0x41) title_cmd(v);                          /* the title: 1 push, 2 pop, 3 empty the top, 4 K/OS */
    if (r == 0x44) title_file_char(v);                    /* the title: the top entry's file -- 0 clears, a character adds */
    if (r >= 0x50 && r <= 0x54) mem_fence_write((uint8_t)(r - 0x50), v);   /* the stack fence */
    if (r == 0x45) io_wait_start();                       /* WAIT: asleep until an interrupt or a key */
    if (r == 0x46) { title_stack[title_depth - 1].resize = (uint8_t)(v & 1); resize_due = 0; }
    if (r == 0x48 && v == 1 && io_vidcap_state != 1) { io_vidcap_req = 1; io_vidcap_state = 1; }   /* VIDCAP: measure */
    if (r == 0x47) {                                      /* PALNAME: the machine loaded a palette */
        if (v == 0xFF) palname_rd = 0;
        else if (v) { if (palname_n < sizeof palname_in - 1) palname_in[palname_n++] = (char) v; }
        else { palname_in[palname_n] = 0; memcpy(io_palname, palname_in, sizeof io_palname); palname_n = 0; io_palname_new = 1; }
    }   /* RESIZE: the wish; a write takes the waiting one */
    if (r == 0x42) idea_add(v);                           /* IDEA: a character of the idea */
    if (r == 0x43) idea_write(v);                         /* IDEA: 1 write it, 2 an empty one for VI */
    if (r == 0x28) adopt_req = 1;                         /* SETUP: keep the clock in force as this host's measured clock */
    if (r == 0x29) measuring = v ? 1 : 0;                 /* SETUP: hold the governor off while the ladder is swept */
    if (r == 0x21) { sys_opts &= (uint8_t)~(SYSOPT_MODEREQ | SYSOPT_MODE); mode_acked = 1;
                     if (title_stack[title_depth - 1].resize) resize_due = 0x80; }
                       /* the guest acknowledging a video-mode request: it has performed it,
                        * so the request goes away at once instead of standing for frames
                        * while every key poll performs it again */
}
int title_depth_now(void) { return title_depth; }
void sys_reset(void) { sys_frames = 0; title_cmd(4); }   /* the title: back to K/OS */
void sys_state_save(FILE *f) { state_put(f, "SYSR", sys_reg, sizeof sys_reg); }
int  sys_state_load(FILE *f) { return state_get(f, "SYSR", sys_reg, sizeof sys_reg); }

/* the title as the top band shows it: "EhBASIC PROG.BAS > VI ...", and
 * the Tube's program while it runs -- asked of the Tube, not stacked,
 * because a `!ls` ends by itself and nothing would pop it -- in the place
 * it started from, so a *VI from BBC BASIC reads "BBC BASIC > VI ...".
 * K/OS is named only when nothing runs on top of it: Doc, 2026-09-14,
 * "once inside a program ... just show BBC Basic > VI (to avoid needlessly
 * long lines)". */
const char *io_title(void)
{
    static char buf[256];
    static const char *const tube_names[] = { "", "BBC BASIC", "", "CP/M", "Linux", "chess engine" };
    int tube = tube_prog_now > 0 && tube_prog_now <= 5 && (tube_status() & 1);
    size_t n = 0;
    buf[0] = 0;
    for (int i = 0; i < title_depth; i++) {
        if (i || (title_depth == 1 && !tube)) {
            n += (size_t) snprintf(buf + n, sizeof buf - n, "%s%s%s%s", n ? " > " : "", title_stack[i].prog,
                                   title_stack[i].file[0] ? " " : "", title_stack[i].file);
            if (n >= sizeof buf) { n = sizeof buf - 1; break; }
        }
        if (tube && i == tube_prog_at - 1 && n < sizeof buf - 20)
            n += (size_t) snprintf(buf + n, sizeof buf - n, "%s%s", n ? " > " : "", tube_names[tube_prog_now]);
    }
    return buf;
}
