#!/usr/bin/env python3
"""Generate the code page appendix from the machine's own table.

core/codepage.h is the one table of the K4510 code page: tools/mkcodepage.py
writes it, and JIM, the keyboard, the fonts and k4510-remote all read it.
This turns it into generated/codepage.tex -- the page as a 16 x 16 grid
with the places where it differs from IBM's code page 437 in bold, then a
list of those places: the byte, the character, its Unicode name, and what
CP437 had there.  "What CP437 had" comes from Python's own cp437 codec, so
the list is a comparison with the real thing, not with a copy of it.

The book says there are 26 such places; if the table ever says otherwise
this stops the build rather than print a book that disagrees with itself.

Run by make-guide.sh.  Output: generated/codepage.tex (never edit).
"""
import os, re, sys, unicodedata

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", ".."))
SRC = os.path.join(ROOT, "core", "codepage.h")
OUT = os.path.join(HERE, "generated", "codepage.tex")
PLACES = 26                                   # what chapters/a4-codepage.tex says


def table():
    text = open(SRC, encoding="utf-8").read()
    body = text[text.index("k4510_cp[256]"):]
    body = body[body.index("{") + 1: body.index("};")]
    body = re.sub(r"/\*.*?\*/", "", body, flags=re.S)
    vals = [int(v, 16) for v in re.findall(r"0x([0-9A-Fa-f]+)", body)]
    if len(vals) != 256:
        sys.exit("mkcodepage: %d values in %s, not 256" % (len(vals), SRC))
    return vals


def cp437(b):
    return ord(bytes([b]).decode("cp437"))


ESC = {"\\": r"\textbackslash{}", "{": r"\{", "}": r"\}", "$": r"\$", "&": r"\&",
       "%": r"\%", "#": r"\#", "_": r"\_", "^": r"\textasciicircum{}", "~": r"\textasciitilde{}"}


def glyph(u):
    if u == 0:
        return ""
    if u == 0x20:
        return r"{\tiny SP}"
    if u == 0xA0:
        return r"{\tiny NB}"
    c = chr(u)
    return ESC.get(c, c)


def uname(u):
    try:
        return unicodedata.name(chr(u)).lower()
    except ValueError:
        return "U+%04X" % u


def main():
    cp = table()
    changed = [b for b in range(0x80, 0x100) if cp[b] != cp437(b)]
    if len(changed) != PLACES:
        sys.exit("mkcodepage: %d places differ from CP437, the book says %d" % (len(changed), PLACES))
    hexd = "0123456789ABCDEF"
    out = []
    w = out.append
    w("% GENERATED by doc/guide/mkcodepage.py -- do not edit.")
    w("% Source: core/codepage.h, compared with Python's cp437 codec.")
    w("")
    w("% not on the machine")                  # mkgem leaves the grid out of BOOK: $01-$1F are controls in a file
    w(r"\noindent Generated from \pth{core/codepage.h}. The row is a byte's high hex digit,")
    w(r"the column its low one: \texttt{\$82} is row 8, column 2. The %d places that" % PLACES)
    w(r"are not CP437's are in bold. \textsc{sp} is the space and \textsc{nb} the")
    w(r"no-break space; \texttt{\$00} draws nothing.\par\medskip")
    w(r"\begin{center}\ttfamily\small")
    w(r"\setlength{\tabcolsep}{2.4pt}\renewcommand{\arraystretch}{1.3}")
    w(r"\begin{tabular}{r|*{16}{c}}")
    w(" & " + " & ".join(r"{\color{kheading}%s}" % h for h in hexd) + r" \\ \hline")
    for r in range(16):
        cells = []
        for c in range(16):
            b = r * 16 + c
            g = glyph(cp[b])
            cells.append(r"\textbf{%s}" % g if b in changed else g)
        w(r"{\color{kheading}%s} & " % hexd[r] + " & ".join(cells) + r" \\")
    w(r"\end{tabular}")
    w(r"\end{center}")
    w("% end not on the machine")
    w("")
    w(r"\subsection*{The %d places}" % PLACES)
    w(r"\begin{center}\small")
    w(r"\begin{tabular}{l c p{0.52\linewidth} c}")         # A5 is narrow: the name wraps, CP437's is left to its glyph
    w(r"\toprule")
    w(r"Byte & \multicolumn{2}{l}{The K4510 page} & CP437 had \\")
    w(r"\midrule")
    for b in changed:
        w(r"\texttt{\$%02X} & \texttt{%s} & %s & \texttt{%s} \\" % (
            b, glyph(cp[b]), uname(cp[b]), glyph(cp437(b))))
    w(r"\bottomrule")
    w(r"\end{tabular}")
    w(r"\end{center}")
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    open(OUT, "w", encoding="utf-8").write("\n".join(out) + "\n")
    print("mkcodepage: %s (%d places not CP437's)" % (os.path.relpath(OUT, HERE), len(changed)))


if __name__ == "__main__":
    main()
