#!/usr/bin/env python3
"""Generate the repository's issue template from the handbook page.

The handbook has a page -- "Filing an Issue" -- whose argument is that an
issue filed here is going to be handed to a coding session as written, so
it should be shaped like a prompt rather than like a form. GitHub needs
the same block, and two copies of a thing like that drift within a month.

So there is one copy, and it is the book's. This lifts the form and the
three checks off that page and writes .github/ISSUE_TEMPLATE/report.md.
Editing the chapter changes both; editing the generated file changes
nothing, because the next build overwrites it.

Run by make-guide.sh. Output: .github/ISSUE_TEMPLATE/report.md (never edit).
"""
import re, sys, pathlib

CHAPTER = "chapters/a2-issues.tex"
FORM = "issue-form.txt"        # the hand-filled block; BUG asks the same
OUT = ".github/ISSUE_TEMPLATE/report.md"
PROGRAM = "demo/bug.c"      # BUG asks the same questions; see check_labels()

# BUG interviews the user at the machine; the block on the page is the same
# report filled in by hand, for someone who never ran it. The two have
# different jobs and neither is generated from the other -- but they must
# not come to ask different things, so this table says which line of the
# page answers which question of the program's bug_labels[], and the guide
# build fails when either side gains or loses one.
#
#   (label in demo/bug.c, line it must appear as on the page)
#
# None = the machine answers it itself and no human is asked, so the page
# has no line for it.
FIELDS = [
    ("Machine",                                   "Machine"),
    ("Version",                                   "Version"),
    ("Screen",                                    None),
    ("Dump",                                      "Dump"),
    ("When",                                      None),
    ("Where were you?",                           "Where"),
    ("What did you type, exactly?",               "What I typed, exactly"),
    ("What happened?",                            "What happened"),
    ("What did you expect instead?",              "What I expected"),
    ("Why did you expect that?",                  "Why I expected it"),
    ("Still wrong with  k4510 --no-startup.bat ?", "Still wrong with"),
    ("Anything else?",                            None),
]

FRONT = """---
name: Report or request
about: One block, filled in. It goes to a coding session as written.
title: ''
labels: ''
assignees: ''
---

<!-- Generated by doc/guide/mkissue.py from doc/guide/issue-form.txt and
     the handbook's "Filing an Issue" appendix. Edit those, not this file:
     the next guide build overwrites it. -->

An issue filed here is handed to an AI coding session to work on, as
written -- so the best issue is the one the machine writes itself.

**At the machine:** type `DUMP ON`, make it go wrong again, then type `BUG`
(or `*BUG` from a BASIC) and answer its questions. It writes
`fs/SYSTEM/BUGREPORTS/BUG-*.TXT`; the dump is in `dumps/`. Attach both.
That report is the whole text of the issue -- nothing below is needed.

**If you have no report file** (a fault in the handbook, a machine that
will not boot, a telephone), the block below asks the same questions. Fill
in what you can and delete what does not apply.

**Before either**, each of which removes a day:

"""

TAIL = """
**Before you attach a dump:** it carries the shell log -- every command line
from that session, and file names from your own disk with them. It is plain
text. Open it and have a look first.

The handbook's "Filing an Issue" appendix says the same at greater length.
"""


def balanced(text, start):
    """The contents of a brace group that may hold brace groups of its own."""
    depth, i = 1, start
    while i < len(text) and depth:
        if text[i] == "{":   depth += 1
        elif text[i] == "}": depth -= 1
        i += 1
    return text[start:i - 1]


def unlatex(t):
    """Enough LaTeX to render one sentence of the book's prose as Markdown."""
    t = t.replace("{-}{-}", "--")          # before any {...} is matched
    t = re.sub(r"\\verb\|([^|]*)\|", r"`\1`", t)
    t = re.sub(r"\\pth\{([^}]*)\}", r"`\1`", t)
    t = re.sub(r"\\texttt\{([^}]*)\}", r"`\1`", t)
    t = re.sub(r"\\emph\{([^}]*)\}", r"*\1*", t)
    t = t.replace("---", "--").replace("``", '"').replace("''", '"')
    return re.sub(r"\s+", " ", t).strip()


def check_labels(root, block):
    """Fail the build if BUG and the page have come to ask different things.

    Absent program: a note, not a failure -- the book must still build in a
    checkout that has no machine in it. Present and disagreeing: a failure,
    which is the whole point of the table."""
    src = root / PROGRAM
    if not src.exists():
        print("issue template: no %s here, labels unchecked" % PROGRAM)
        return True
    text = src.read_text()
    m = re.search(r"bug_labels\[\]\s*=\s*\{(.*?)\}", text, re.S)
    if not m:
        print("mkissue: no bug_labels[] in %s" % PROGRAM, file=sys.stderr)
        return False
    found = re.findall(r'"((?:[^"\\]|\\.)*)"', m.group(1))
    want = [prog for prog, _ in FIELDS]
    if found != want:
        print("mkissue: %s asks different things than the page knows about."
              % PROGRAM, file=sys.stderr)
        for label in [l for l in found if l not in want]:
            print("  new question, page and FIELDS need it:  %r" % label,
                  file=sys.stderr)
        for label in [l for l in want if l not in found]:
            print("  gone from the program, still in FIELDS: %r" % label,
                  file=sys.stderr)
        if sorted(found) == sorted(want):
            print("  (same questions, different order)", file=sys.stderr)
        return False

    ok = True
    lines = [l.lstrip() for l in block.split("\n")]
    for prog, page in FIELDS:
        if page and not any(l.startswith(page) for l in lines):
            print("mkissue: BUG asks %r; the page has no %r line"
                  % (prog, page), file=sys.stderr)
            ok = False
    return ok


def main():
    here = pathlib.Path(__file__).parent
    root = here.resolve().parents[1]
    src = (here / CHAPTER).read_text()

    # the three leads of "Three things first" -- the bold sentence of each
    start = src.index("\\section{Before you try again}")
    nxt = src.index("\\section{", start + 1)      # whatever section follows it
    section = src[start:nxt]
    checks = [balanced(section, m.end()) for m in re.finditer(r"\\textbf\{", section)]
    if not checks:
        print("mkissue: no bold leads under 'Before you try again'", file=sys.stderr)
        return 1

    form = (here / FORM).read_text()

    if not check_labels(root, form):
        print("mkissue: fix the page, or FIELDS in this script, and rebuild.",
              file=sys.stderr)
        return 1

    out = [FRONT]
    out += ["- %s\n" % unlatex(c) for c in checks]
    out += ["\n```\n", form, "```\n", TAIL]
    dest = root / OUT
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text("".join(out))
    print("issue template: %s" % OUT)
    return 0

sys.exit(main())
