#!/usr/bin/env python3
"""doc/guide/mkship.py -- SHIPPING.cfg, as something LaTeX can read.

Writes generated/shipping.tex: one \\shipnope{key} line per thing marked `nope'
in SHIPPING.cfg (tools/mkmanifest.py keeps that file).  style/k4510.sty defines
\\shipif{key}{...}, which prints its content unless the key was declared nope.

The list is of what to LEAVE OUT, never of what to keep.  A key that is absent,
misspelt or new is therefore printed: the failure mode of this switch is a book
that says too much, never a book that silently drops a chapter.  Doc, on the
qualifiers: "Nope does not imply that we delete it from the repo".

Run by make-guide.sh before xelatex.  mkweb.py reads SHIPPING.cfg directly for
the web and the machine's own pages, so all three editions hide the same things.
"""
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
REPO = HERE.parent.parent
OUT = HERE / "generated"


def nope_keys():
    """The keys marked nope in SHIPPING.cfg; an absent file hides nothing."""
    cfg = REPO / "SHIPPING.cfg"
    out = []
    if cfg.is_file():
        for line in cfg.read_text().splitlines():
            line = line.split("#", 1)[0].strip()
            if "=" in line:
                k, v = (x.strip() for x in line.split("=", 1))
                if v == "nope":
                    out.append(k)
    return out


def main():
    keys = nope_keys()
    OUT.mkdir(exist_ok=True)
    body = ["% generated by doc/guide/mkship.py from SHIPPING.cfg -- never edit",
            "% Each line declares one thing the build was told to leave out."]
    body += ["\\shipnope{" + k + "}" for k in keys]
    (OUT / "shipping.tex").write_text("\n".join(body) + "\n")
    print(f"mkship: {len(keys)} thing(s) marked nope" + (": " + ", ".join(keys) if keys else ""))


if __name__ == "__main__":
    main()
