#!/bin/sh
# Lay out an SD card for the BMC-K4510: firmware + kernel8.img at the root,
# the machine's files under /k4510.  Usage: pi/make-sd.sh /path/to/mounted/card
set -e
M="$1"; [ -d "$M" ] || { echo "usage: $0 /mounted/card"; exit 1; }
HERE=$(cd "$(dirname "$0")" && pwd); REPO=$(cd "$HERE/.." && pwd)
# rom/kernal.bin is built by cc65 and is NOT in the repository, so it does not
# arrive with a git pull, and it cannot be rebuilt on a host without cc65 --
# which is p15, the host that writes the cards.  A card laid out with last
# week's ROM boots and looks perfectly right, which is the worst kind of wrong:
# it happened on 2026-08-27, when the ROM on the card was a day behind the ROM
# in the repository and nothing said so.  Refuse instead.
K="$REPO/rom/kernal.bin"
[ -f "$K" ] || { echo "make-sd: $K is missing."; echo "  Build the ROM where cc65 lives (t480i5, ubuntu-s1) and copy it here."; exit 1; }
for src in "$REPO"/rom/kernal.c "$REPO"/rom/*.s "$REPO"/rom/*.cfg; do
    [ -f "$src" ] || continue
    if [ -n "$(find "$src" -newer "$K" 2>/dev/null)" ]; then
        echo "make-sd: rom/kernal.bin is older than $(basename "$src") -- the card would carry a stale ROM."
        if command -v cc65 >/dev/null 2>&1; then
            echo "  cc65 is on this host: run 'make' first."
        else
            echo "  There is no cc65 on this host, so 'make' cannot fix it here: build the"
            echo "  ROM on t480i5 or ubuntu-s1 and copy rom/kernal.bin over."
        fi
        if [ "${MAKE_SD_STALE_ROM:-0}" = 1 ]; then
            echo "  MAKE_SD_STALE_ROM=1: laying the card out with the stale ROM anyway."
        else
            echo "  To lay out the card anyway: MAKE_SD_STALE_ROM=1 $0 \"$M\""
            exit 1
        fi
    fi
done

B="${SHIM:-$HOME/Projects/k4510-pi/circle-libsdl2}/circle-stdlib-rpi3/libs/circle/boot"
cp "$B/bootcode.bin" "$B/start.elf" "$B/fixup.dat" "$M/"
cp "$HERE/config.txt" "$M/config.txt"
# Circle reads cmdline.txt for its kernel options, and keymap= is one of them.
# Without the file it falls back to sysconfig.h's DEFAULT_KEYMAP, which in this
# Circle is "DE" -- so a USB keyboard came up German, with y and z swapped
# (Doc, 2026-09-01, on real hardware).  keymap_us.h is already compiled in, so
# this is the whole fix; no Circle rebuild.
#
# The file must have NO trailing newline.  Circle's CKernelOptions::GetToken
# splits the command line on ' ' and nothing else, so a newline stays inside
# the value: "keymap=us\n" looks up a locale called "us\n", finds nothing, and
# falls back to DEFAULT_KEYMAP -- which is how the first attempt at this fix
# still came up German.
cp "$HERE/cmdline.txt" "$M/cmdline.txt"
cp "$HERE/kernel8.img" "$M/kernel8.img"
mkdir -p "$M/k4510/rom" "$M/k4510/data" "$M/k4510/fs"
cp "$REPO/rom/kernal.bin" "$REPO/rom/wozmon.bin" "$REPO/rom/demo.bin" "$M/k4510/rom/"
cp "$REPO/data/font8.bin" "$M/k4510/data/"
# The alternate screen fonts, so F7 -> Screen font works on the Pi too (not
# just kernel8).  -L to dereference; whatever is present here is carried,
# including data/fonts/zx (the ZX Origins fonts you regenerated locally --
# personal use on your own card, they are not in the repo).
[ -d "$REPO/data/fonts" ] && cp -rL "$REPO/data/fonts" "$M/k4510/data/"
# -L because FAT32 has no symlinks.  fs/CPM is the
# exception and is done below: its drive letters are links that cannot be
# followed -- K:/0 is deliberately cyclic (it *is* this filesystem) and
# D:/P: point into a CP/M library that is installed but never committed.
# The dotfiles as well as the visible ones: fs/.HELP is the shell's help text,
# and a * glob does not match it.  A card that carries last month's .HELP
# documents a command set the ROM on it no longer has -- RANGER, DELETE and
# MSBASIC were all missing from the card's help while being present on it.
for d in "$REPO"/fs/* "$REPO"/fs/.[!.]*; do
    [ -e "$d" ] || continue
    [ "$(basename "$d")" = CPM ] || cp -rL "$d" "$M/k4510/fs/"
done

# The CP/M drives get exactly what the repository itself ships: our .SUB
# launchers and the README.  The system disk (DRI's tools and friends),
# WordStar and Turbo Pascal are installed by whoever has a licence for
# them -- fs/CPM/.gitignore says how -- so the card leaves their drives
# empty rather than redistributing them.
mkdir -p "$M/k4510/fs/CPM/A/0" "$M/k4510/fs/CPM/D/0" \
         "$M/k4510/fs/CPM/K/0" "$M/k4510/fs/CPM/P/0"
git -C "$REPO" ls-files -z fs/CPM | while IFS= read -r -d "" f; do
    [ -L "$REPO/$f" ] && continue
    mkdir -p "$M/k4510/$(dirname "$f")"
    cp "$REPO/$f" "$M/k4510/$f"
done
cp "$REPO/basic/README-EhBASIC.txt" "$M/k4510/"

# The card says what it is and which build it carries.  core/build.h is
# generated by the build, so the stamp cannot drift from the kernel.
cp "$HERE/README-SD.txt" "$M/README.txt"
if [ -f "$REPO/core/build.h" ]; then
    STAMP=$(sed -n 's/.*K4510_BUILD "\(.*\)".*/\1/p' "$REPO/core/build.h")
    [ -n "$STAMP" ] && printf '\nTHIS CARD\n  Build %s, laid out %s.\n' \
        "$STAMP" "$(date +%Y-%m-%d)" >> "$M/README.txt"
fi
sync
echo "card ready:"; ls -R "$M" | head -40
