#!/usr/bin/env python3
"""KoboChess's drawn pieces -> VICKY: data/chess/ -> demo/chess.bin + demo/chess.h

chess.bin, dropped at CHESS_PHYS by the K4SG header: 64x64 4 bpp sprites,
2048 bytes each (two pixels a byte, high nibble left).  0-5 white P N B R
Q K, 6-11 black, then the markers: 12 a square frame (3 px), 13 a dot,
14 a thin frame; then twelve 16x16 minis (CH_MINI_OFF) for the captured
trays.  The 44x44 piece sits centred in the 64x64 sprite so it
is 10 px inside a 48 px square with the sprite placed 8 px up and left.

Pixel classes, so a palette bank can colour a side: 1 ink (the black of
the drawing, full alpha), 2 paper (the white inside), 3 edge (ink at part
alpha: the anti-aliasing, drawn in a tone between ink and the square).
The markers use 1, 2 and 3 of their own bank (frame, dot, thin frame)."""
import os
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "..", "data", "chess")
OUT = os.path.join(HERE, "..", "demo")
S = 64; P = 44; OFF = (S - P) // 2
def classify(px):
    r, g, b, a = px
    if a < 48: return 0
    lum = (r * 299 + g * 587 + b * 114) // 1000
    if lum >= 128: return 2 if a >= 160 else 3
    return 1 if a >= 160 else 3
def pack(pix):
    out = bytearray()
    for i in range(0, len(pix), 2): out.append((pix[i] << 4) | pix[i + 1])
    return out
data = bytearray()
for side in "wb":
    for kind in "pnbrqk":
        im = Image.open(os.path.join(SRC, f"{side}{kind}.png")).convert("RGBA")
        assert im.size == (P, P), im.size
        pix = [0] * (S * S)
        for y in range(P):
            for x in range(P): pix[(y + OFF) * S + x + OFF] = classify(im.getpixel((x, y)))
        data += pack(pix)
def frame(th, val):
    pix = [0] * (S * S)
    for y in range(8, 56):
        for x in range(8, 56):
            if x < 8 + th or x >= 56 - th or y < 8 + th or y >= 56 - th: pix[y * S + x] = val
    return pack(pix)
def dot(r, val):
    pix = [0] * (S * S)
    for y in range(S):
        for x in range(S):
            if (x - 31.5) ** 2 + (y - 31.5) ** 2 <= r * r: pix[y * S + x] = val
    return pack(pix)
data += frame(3, 1) + dot(7, 2) + frame(2, 3)
# the captured-piece trays: every piece again at 14 px in a 16x16 4 bpp
# sprite (128 bytes), downscaled from the same drawings
MINI_OFF = len(data)
for side in "wb":
    for kind in "pnbrqk":
        im = Image.open(os.path.join(SRC, f"{side}{kind}.png")).convert("RGBA").resize((14, 14), Image.LANCZOS)
        pix = [0] * 256
        for y in range(14):
            for x in range(14): pix[(y + 1) * 16 + x + 1] = classify(im.getpixel((x, y)))
        data += pack(pix)
open(os.path.join(OUT, "chess.bin"), "wb").write(bytes(data))
with open(os.path.join(OUT, "chess.h"), "w") as f:
    f.write("/* generated by tools/mkchess.py from data/chess -- do not edit.\n * The KoboChess drawn set, by Doc. */\n")
    f.write("#define CH_SPR_BYTES 2048UL\n#define CH_MARK_FRAME 12\n#define CH_MARK_DOT 13\n#define CH_MARK_THIN 14\n")
    f.write(f"#define CH_MINI_OFF {MINI_OFF}UL\n#define CH_MINI_BYTES 128UL\n")
print(f"chess.bin: {len(data)} bytes, 15 sprites")
