#!/usr/bin/env python3
"""tools/mkcodepage.py -- write core/codepage.h, the K4510 code page.

CP437 (IBM's), with 26 of its least-used places given to what Western
European languages lack in it: the accented capitals of French, Italian
and Spanish, oe/OE, the euro, the section and paragraph signs, German
quotes, and o-slash.  Kept as CP437: the box drawing, shades and blocks,
every accented letter it had, sharp s, micro, plus-minus, divide, degree,
middle dot, superscript two, the square, no-break space.  The plan and its
reasons: docs/K4510-CODEPAGE.md (Doc, 2026-09-15: "go with the German
quotes").  $01-$1F keep CP437's pictures, as the font draws them.

    tools/mkcodepage.py > core/codepage.h
"""
import sys

LOW = [0x0000, 0x263A, 0x263B, 0x2665, 0x2666, 0x2663, 0x2660, 0x2022, 0x25D8, 0x25CB, 0x25D9, 0x2642, 0x2640,
       0x266A, 0x266B, 0x263C, 0x25BA, 0x25C4, 0x2195, 0x203C, 0x00B6, 0x00A7, 0x25AC, 0x21A8, 0x2191, 0x2193,
       0x2192, 0x2190, 0x221F, 0x2194, 0x25B2, 0x25BC]
NEW = {  # place: character, in place of CP437's
    0x9E: "€", 0x9F: "§", 0xA9: "¶",                       # euro, section, pilcrow (were peseta, f-hook, reversed not)
    0xE0: "À", 0xE2: "Â", 0xE3: "È", 0xE4: "Ê", 0xE5: "Ë", 0xE7: "Î", 0xE8: "Ï",
    0xE9: "Ô", 0xEA: "Ù", 0xEB: "Û", 0xEC: "Ÿ", 0xED: "Á", 0xEE: "Í", 0xEF: "Ó",
    0xF0: "Ú", 0xF2: "Ì", 0xF3: "Ò",                        # the accented capitals (were Greek and maths)
    0xF4: "œ", 0xF5: "Œ", 0xF7: "ø", 0xF9: "Ø",        # oe OE o/ O/
    0xFB: "„", 0xFC: "“",                                        # German quotes
}

def table():
    t = list(LOW) + list(range(0x20, 0x7F)) + [0x2302]
    for b in range(0x80, 0x100):
        t.append(ord(NEW[b]) if b in NEW else ord(bytes([b]).decode("cp437")))
    hi = t[0x80:]
    assert len(t) == 256 and len(set(hi)) == 128, "a character twice in the upper half"
    return t

def main():
    t = table()
    w = sys.stdout.write
    w("/* core/codepage.h -- GENERATED by tools/mkcodepage.py; do not edit.\n"
      " * The K4510 code page: each byte as Unicode.  CP437 with 26 places given to\n"
      " * the letters Western Europe needs (docs/K4510-CODEPAGE.md).  $00-$1F and $7F\n"
      " * are what the font draws there (CP437's pictures); as text they are controls. */\n"
      "#ifndef K4510_CODEPAGE_H\n#define K4510_CODEPAGE_H\n#include <stdint.h>\n"
      "static const uint16_t k4510_cp[256] = {\n")
    for r in range(0, 256, 8):
        w("    " + ", ".join("0x%04X" % u for u in t[r:r + 8]) + ",   /* $%02X */\n" % r)
    w("};\n#endif\n")

if __name__ == "__main__":
    main()
