#!/usr/bin/env python3
"""Generate core/kbdmaps.h: the K4510's own keyboard layouts (F7 -> Input ->
Keyboard layout), so a layout takes effect the moment it is chosen and matches
the Linux consoles key for key -- both come from XKB.

Source: Debian's ckbcomp (console-setup), which compiles an XKB layout into a
kernel keymap: per Linux keycode the plain, Shift, AltGr and Shift+AltGr
symbols, '+' on a letter Caps Lock affects, and dead_* for dead keys.  ckbcomp
lists no compositions, so those come from Unicode: a dead accent plus a base
letter is the NFC composition of the letter and the combining mark.

    python3 tools/mkkbdmaps.py > core/kbdmaps.h

Doc, 2026-09-12: "I want a selectable keyboard layout in the K4510, reflected
immediately after selection, and the host in sync."
"""
import re
import subprocess
import sys
import unicodedata

# (menu name, XKB layout, XKB variant) -- the order is the setting's, after "Host"
LAYOUTS = [
    ("US", "us", ""), ("US-intl", "us", "intl"), ("Canada-FR", "ca", ""), ("France", "fr", ""),
    ("Germany", "de", ""), ("Spain", "es", ""), ("UK", "gb", ""), ("Italy", "it", ""),
]
# dead keysym -> (the spacing accent it types alone, the combining mark)
DEAD = {
    "dead_grave": (0x60, 0x300), "dead_acute": (0xB4, 0x301), "dead_circumflex": (0x5E, 0x302),
    "dead_tilde": (0x7E, 0x303), "dead_diaeresis": (0xA8, 0x308), "dead_cedilla": (0xB8, 0x327),
    "dead_abovering": (0x2DA, 0x30A),
}
KBD_DEAD, KBD_CAPS = 0x80000000, 0x40000000


def symbol(tok):
    """one ckbcomp symbol -> table value (0: types nothing we can show)"""
    caps = tok.startswith("+")
    tok = tok.lstrip("+")
    m = re.fullmatch(r"U\+([0-9a-fA-F]{4,6})", tok)
    if m:
        u = int(m.group(1), 16)
        if u < 0x20 or u == 0x7F:
            return 0
        return u | (KBD_CAPS if caps else 0)
    if tok in DEAD:
        return KBD_DEAD | DEAD[tok][0]
    return 0


def layout_table(layout, variant):
    cmd = ["ckbcomp", "-layout", layout, "-compact"] + (["-variant", variant] if variant else [])
    out = subprocess.run(cmd, capture_output=True, text=True, check=True).stdout
    tab = [[0, 0, 0, 0] for _ in range(128)]
    for line in out.splitlines():
        m = re.match(r"keycode\s+(\d+)\s*=\s*(.*)", line)
        if not m or int(m.group(1)) >= 128:
            continue
        syms = m.group(2).split()
        vals = [symbol(s) for s in syms[:4]] + [0] * (4 - min(4, len(syms)))
        # the Caps flag rides on the plain entry: Caps Lock swaps the shift level of a letter
        if vals[0] and not vals[0] & KBD_DEAD and syms and syms[0].startswith("+"):
            vals[0] |= KBD_CAPS
        tab[int(m.group(1))] = vals
    return tab


def compositions():
    rows = []
    bases = [ord(c) for c in "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"]
    for name, (spacing, mark) in DEAD.items():
        rows.append((spacing, 0x20, spacing))                  # accent, then space: the accent itself
        for b in bases:
            c = unicodedata.normalize("NFC", chr(b) + chr(mark))
            if len(c) == 1:
                rows.append((spacing, b, ord(c)))
    return rows


def main():
    w = sys.stdout.write
    w("/* core/kbdmaps.h -- GENERATED by tools/mkkbdmaps.py from XKB via ckbcomp; do not edit.\n"
      " * The K4510's keyboard layouts (F7 -> Input -> Keyboard layout): per Linux keycode,\n"
      " * [plain, Shift, AltGr, Shift+AltGr] as Unicode; KBD_DEAD = a dead key (the low\n"
      " * bits are the accent it types alone), KBD_CAPS on the plain entry = a letter\n"
      " * Caps Lock shifts.  Then the dead-key compositions, from Unicode NFC. */\n")
    w("#ifndef K4510_KBDMAPS_H\n#define K4510_KBDMAPS_H\n#include <stdint.h>\n")
    w("#define KBD_DEAD 0x80000000u\n#define KBD_CAPS 0x40000000u\n#define KBD_CHAR 0x001FFFFFu\n")
    w("#define KBD_MAPS %d\n" % len(LAYOUTS))
    w("static const char *const kbd_map_names[KBD_MAPS] = { %s };\n" % ", ".join('"%s"' % n for n, _, _ in LAYOUTS))
    w("static const uint32_t kbd_maps[KBD_MAPS][128][4] = {\n")
    for name, layout, variant in LAYOUTS:
        tab = layout_table(layout, variant)
        w("  { /* %s: xkb %s%s */\n" % (name, layout, ("(" + variant + ")") if variant else ""))
        for kc in range(128):
            if any(tab[kc]):
                w("    [%d] = { 0x%08X, 0x%08X, 0x%08X, 0x%08X },\n" % ((kc,) + tuple(tab[kc])))
        w("  },\n")
    w("};\n")
    rows = compositions()
    w("static const struct { uint16_t dead, base, out; } kbd_compose[%d] = {\n" % len(rows))
    for i in range(0, len(rows), 6):
        w("   " + " ".join("{ 0x%04X, 0x%04X, 0x%04X }," % r for r in rows[i:i + 6]) + "\n")
    w("};\n#endif\n")


if __name__ == "__main__":
    main()
