#!/usr/bin/env python3
"""mknvim.py -- Neovim's syntax files for the machine's own languages, made
from the languages themselves so the two can never disagree:

  tools/nvim/syntax/k4510basic.vim   EhBASIC's keyword table (basic/basic.asm)
  tools/nvim/syntax/k4510logo.vim    LOGO's words (demo/logo.c)

Run by make; the outputs are tracked, so the K4510 Linux needs no Python for
them.  BBC BASIC (the Tube's) and REXX have theirs by hand / from Neovim.
"""
import os, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "tools", "nvim", "syntax")


def wrap(group, words):
    lines, cur = [], []
    for w in words:
        cur.append(w)
        if len(" ".join(cur)) > 70:
            lines.append(f"syn keyword {group} " + " ".join(cur)); cur = []
    if cur:
        lines.append(f"syn keyword {group} " + " ".join(cur))
    return "\n".join(lines)


def basic():
    asm = open(os.path.join(ROOT, "basic", "basic.asm"), encoding="latin-1").read()
    # each entry: .byte "REST",TK_NAME   ; KEYWORD  -- the comment may be on the next line
    stmts, funcs = set(), set()
    for m in re.finditer(r'\.byte\s+"[^"]*",\s*TK_\w+\s*(?:\n\s*)?;\s*([A-Z][A-Z0-9$]*)(\(?)', asm):
        (funcs if m.group(2) else stmts).add(m.group(1))
    stmts -= {"REM", "DATA"}
    if len(stmts) + len(funcs) < 60:
        raise SystemExit(f"mknvim: only {len(stmts) + len(funcs)} BASIC keywords found -- has basic.asm's table changed?")
    return f'''" generated by tools/mknvim.py from basic/basic.asm's keyword table -- never edit
" BASIC as the machine has it: EhBASIC with its graphics and sprites, and
" Microsoft's 1977 BASIC (.BAS; MSBASIC runs them from NVIM's :Run)
if exists("b:current_syntax") | finish | endif
syn case ignore
syn iskeyword @,48-57,_,$
{wrap("k4basicStatement", sorted(stmts))}
{wrap("k4basicFunction", sorted(funcs))}
syn match k4basicLineNr "^\\s*\\d\\+"
syn match k4basicNumber "\\<\\d\\+\\(\\.\\d*\\)\\?\\([eE][-+]\\?\\d\\+\\)\\?\\>"
syn match k4basicNumber "\\$\\x\\+\\>"
syn match k4basicNumber "%[01]\\+\\>"
syn region k4basicString start=+"+ end=+"+ oneline
syn match k4basicComment "\\<REM\\>.*$"
syn match k4basicData "\\<DATA\\>.*$"
hi def link k4basicStatement Statement
hi def link k4basicFunction  Function
hi def link k4basicLineNr    LineNr
hi def link k4basicNumber    Number
hi def link k4basicString    String
hi def link k4basicComment   Comment
hi def link k4basicData      Constant
let b:current_syntax = "k4510basic"
''', len(stmts) + len(funcs)


def logo():
    src = open(os.path.join(ROOT, "demo", "logo.c"), encoding="latin-1").read()
    words = set(re.findall(r'strcmp\(\s*\w+\s*,\s*"([A-Z][A-Z0-9.?]*)"\s*\)', src))
    if len(words) < 30:
        raise SystemExit(f"mknvim: only {len(words)} LOGO words found -- has demo/logo.c changed?")
    ctrl = {w for w in words if w in {"TO", "END", "REPEAT", "IF", "IFELSE", "STOP", "OUTPUT", "OP", "MAKE", "LOCAL", "FOREVER", "WHILE", "FOR"}}
    return f'''" generated by tools/mknvim.py from demo/logo.c's words -- never edit
" LOGO as the machine has it (.LGO; LOGO runs them from NVIM's :Run)
if exists("b:current_syntax") | finish | endif
syn case ignore
syn iskeyword @,48-57,_,?,.
{wrap("k4logoControl", sorted(ctrl))}
{wrap("k4logoWord", sorted(words - ctrl))}
syn match k4logoVar ":[A-Za-z_][A-Za-z0-9_.]*"
syn match k4logoQuoted +"[A-Za-z_][A-Za-z0-9_.?]*+
syn match k4logoNumber "\\<\\d\\+\\(\\.\\d*\\)\\?\\>"
syn match k4logoComment ";.*$"
hi def link k4logoControl Statement
hi def link k4logoWord    Function
hi def link k4logoVar     Identifier
hi def link k4logoQuoted  String
hi def link k4logoNumber  Number
hi def link k4logoComment Comment
let b:current_syntax = "k4510logo"
''', len(words)


def put(name, text):
    p = os.path.join(OUT, name)
    old = open(p).read() if os.path.exists(p) else None
    if old != text:
        with open(p, "w") as f:
            f.write(text)


if __name__ == "__main__":
    os.makedirs(OUT, exist_ok=True)
    b, nb = basic(); put("k4510basic.vim", b)
    l, nl = logo(); put("k4510logo.vim", l)
    print(f"mknvim: {nb} BASIC keywords, {nl} LOGO words")
