#!/usr/bin/env python3
"""Kenney's Pixel Shmup -> VICKY: data/pixelshmup/ -> demo/skyfire.bin + demo/skyfire.h

skyfire.bin, dropped at SKY_PHYS by the K4SG header:
   +0            the planes: SKY_NSHIP x 32x32 at 8 bpp, 1024 bytes each
                 (sprite DATA points here), in the order of ship_ids below
   +SKY_TILES    the tiles: 120 x 16x16 at 8 bpp, 256 bytes each -- the
                 ground (layer 0) and, as 16x16 sprites, shots and bursts
   +SKY_MAP      the ground: 20 x 64 entries, 2 bytes each, the lower 32
                 rows repeated so a scroll of 512 px lands on the same picture
skyfire.h: the palette (indices SKY_BASE..), the sizes, the tile numbers.
Pixel indices start at SKY_BASE so the console's own colours survive."""
import os, struct, random
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "..", "data", "pixelshmup")
OUT = os.path.join(HERE, "..", "demo")
BASE = 32
ship_ids = [0, 5, 7, 9, 10, 12, 4]          # player, red, yellow, red-b, green-b, grey bomber, blue small
pal = {}
def idx(px):
    if px[3] < 128: return 0
    rgb = px[:3]
    if rgb not in pal: pal[rgb] = BASE + len(pal)
    return pal[rgb]
def cut(im, x0, y0, w, h):
    b = bytearray()
    for y in range(h):
        for x in range(w): b.append(idx(im.getpixel((x0 + x, y0 + y))))
    return b

ships = Image.open(os.path.join(SRC, "ships_packed.png")).convert("RGBA")
tiles = Image.open(os.path.join(SRC, "tiles_packed.png")).convert("RGBA")
shipdat = bytearray()
for s in ship_ids:
    r, c = divmod(s, 4); shipdat += cut(ships, c * 32, r * 32, 32, 32)
tiledat = bytearray()
for t in range(120):
    r, c = divmod(t, 12); tiledat += cut(tiles, c * 16, r * 16, 16, 16)
assert BASE + len(pal) < 255, len(pal)

# the ground: sea, islands of green or brown with the sheet's 3x3 edge
# blocks, trees and houses inland, a few islets.  32 rows, then repeated.
random.seed(4510)
W, H = 20, 32
SEA = 42
GREEN = [[37, 38, 39], [49, 50, 51], [61, 62, 63]]
BROWN = [[43, 44, 45], [55, 56, 57], [67, 68, 69]]
grid = [[SEA] * W for _ in range(H)]
used = [[0] * W for _ in range(H)]
def island(x0, y0, w, h, blk, decor):
    for y in range(h):
        for x in range(w):
            ry = 0 if y == 0 else 2 if y == h - 1 else 1
            rx = 0 if x == 0 else 2 if x == w - 1 else 1
            yy = (y0 + y) % H
            grid[yy][x0 + x] = blk[ry][rx]; used[yy][x0 + x] = 1
    for y in range(1, h - 1):
        for x in range(1, w - 1):
            if random.random() < 0.18: grid[(y0 + y) % H][x0 + x] = random.choice(decor)
placed = 0; tries = 0
while placed < 9 and tries < 400:
    tries += 1
    w, h = random.randint(3, 6), random.randint(3, 6)
    x0, y0 = random.randint(0, W - w), random.randint(0, H - 1)
    if any(used[(y0 + y) % H][x0 + x] for y in range(-1, h + 1) for x in range(max(0, x0 - 1) - x0, min(W, x0 + w + 1) - x0)):
        continue
    green = random.random() < 0.6
    island(x0, y0, w, h, GREEN if green else BROWN, [36, 48, 60, 66, 72, 84, 96] if green else [46, 58, 70, 78, 90, 102])
    placed += 1
for _ in range(10):
    x, y = random.randrange(W), random.randrange(H)
    if not used[y][x] and not any(used[(y + dy) % H][x + dx] for dy in (-1, 0, 1) for dx in (-1, 0, 1) if 0 <= x + dx < W):
        grid[y][x] = random.choice([64, 65, 71, 40, 53]); used[y][x] = 1
mp = bytearray()
for y in range(H * 2):
    for x in range(W): mp += struct.pack("<H", grid[y % H][x])

bin_ = bytes(shipdat) + bytes(tiledat) + bytes(mp)
open(os.path.join(OUT, "skyfire.bin"), "wb").write(bin_)
with open(os.path.join(OUT, "skyfire.h"), "w") as f:
    f.write("/* generated by tools/mkskyfire.py from data/pixelshmup -- do not edit.\n * Pixel Shmup by Kenney, CC0. */\n")
    f.write(f"#define SKY_BASE {BASE}\n#define SKY_NCOL {len(pal)}\n#define SKY_NSHIP {len(ship_ids)}\n")
    f.write(f"#define SKY_TILES {len(shipdat)}UL\n#define SKY_MAP {len(shipdat) + len(tiledat)}UL\n")
    f.write(f"#define SKY_MAPW {W}\n#define SKY_MAPH {H * 2}\n#define SKY_PERIOD {H * 16}\n")
    f.write("/* ships, in skyfire.bin order */\n#define SH_PLAYER 0\n#define SH_RED 1\n#define SH_YELLOW 2\n#define SH_REDB 3\n#define SH_GREENB 4\n#define SH_BOMBER 5\n#define SH_BLUE 6\n")
    f.write("/* tiles used as sprites */\n#define T_SHOT 0\n#define T_BOMB 12\n#define T_BURST0 4\n#define T_BURST1 5\n#define T_BURST2 6\n#define T_PUFF 8\n")
    f.write("static const uint8_t sky_pal[SKY_NCOL][3] = {")
    f.write(",".join("{%d,%d,%d}" % rgb for rgb, _ in sorted(pal.items(), key=lambda kv: kv[1])))
    f.write("};\n")
print(f"skyfire.bin: {len(shipdat)} ship + {len(tiledat)} tile + {len(mp)} map = {len(bin_)} bytes; {len(pal)} colours; {placed} islands")
